#!/usr/bin/env python3
r"""Publish the thesis to Overleaf as a git branch whose root *is* the project.

Overleaf wants main.tex at the root of its project. This repository keeps the
thesis in thesis/, next to the simulation code -- and thesis/ additionally
carries the working trail: superseded chapter drafts (chapters/_*.tex), the
review-response appendices main.tex no longer includes, LaTeX build artefacts,
CHANGELOG.md, RERUN_CHANGELOG.md, ak_comments.json, submission/. Pushing
thesis/ wholesale, as `git subtree push --prefix=thesis` did, put all of that
into the authoring surface.

This publishes the *document* instead: the transitive closure of main.tex, with
the \REV{...} fix records stripped, on a dedicated branch (default
`overleaf-dist`) whose root is the project root. Overleaf's remote then gets a
clean thesis and nothing else.

    python3 scripts/overleaf_sync.py            # rebuild + commit the branch
    python3 scripts/overleaf_sync.py --push     # ... and push it to Overleaf
    python3 scripts/overleaf_sync.py --show     # what the branch would contain

The sync is ONE-WAY by construction. Stripping annotations is lossy, so an
Overleaf-side edit cannot be replayed into thesis/ automatically. To keep that
from silently destroying anyone's work, --push refuses when the remote carries
commits this branch does not, and prints them; port those edits into thesis/ by
hand, re-run, and push again. --force overrides, discarding them.
"""
import argparse
import os
import shutil
import subprocess
import sys
import tempfile

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from overleaf_project import ROOT, manifest, stage

EMPTY_TREE = "4b825dc642cb6eb9a060e54bf8d69288fbee4904"
DEFAULT_BRANCH = "overleaf-dist"
DEFAULT_REMOTE = "overleaf"
REPO_REMOTE = "thesis-repo"
REPO_BRANCH = "main"
REPO_HINT = ("git remote add thesis-repo "
             "https://github.com/<you>/relaynet2-thesis")


def git(*args, check=True, capture=True):
    r = subprocess.run(["git", "-C", ROOT, *args],
                       capture_output=capture, text=True)
    if check and r.returncode:
        raise SystemExit(f"git {' '.join(args)} failed:\n{r.stderr or r.stdout}")
    return (r.stdout or "").strip()


def branch_exists(branch):
    return subprocess.run(["git", "-C", ROOT, "show-ref", "--verify", "--quiet",
                           f"refs/heads/{branch}"]).returncode == 0


def ensure_branch(branch):
    """Create `branch` as a root commit with an empty tree if it is not there.

    An orphan branch without checking one out: commit-tree against the empty
    tree, then point a ref at it.
    """
    if branch_exists(branch):
        return False
    sha = git("commit-tree", EMPTY_TREE, "-m",
              f"Initialise {branch}: generated Overleaf project root")
    git("branch", branch, sha)
    return True


def publish(branch, mode):
    """Rebuild the branch's tree from thesis/. Returns (changed, sha, n_files)."""
    man = manifest()
    wt = tempfile.mkdtemp(prefix="overleaf_wt_")
    os.rmdir(wt)                       # git worktree add wants a fresh path
    git("worktree", "add", "--quiet", wt, branch)
    try:
        for entry in os.listdir(wt):
            if entry == ".git":
                continue
            p = os.path.join(wt, entry)
            shutil.rmtree(p) if os.path.isdir(p) else os.remove(p)
        stage(wt, mode, man)

        subprocess.run(["git", "-C", wt, "add", "-A"], check=True)
        staged = subprocess.run(["git", "-C", wt, "diff", "--cached", "--quiet"])
        n_files = len(subprocess.run(
            ["git", "-C", wt, "ls-files"], capture_output=True, text=True,
            check=True).stdout.split())
        if staged.returncode == 0:
            return False, git("rev-parse", branch), n_files

        src = git("rev-parse", "--short", "HEAD")
        subject = git("log", "-1", "--format=%s", "HEAD")
        subprocess.run(
            ["git", "-C", wt, "commit", "--quiet", "-m",
             f"Thesis at {src} ({mode})\n\n"
             f"Generated by scripts/overleaf_sync.py from thesis/ at {src}: "
             f"{subject}\n"
             f"{len(man['chapters'])} chapters, {len(man['figures'])} figures, "
             f"{len(man['styles'])} local style file(s).\n"
             f"Do not edit this branch by hand -- it is regenerated in full."],
            check=True)
        return True, git("rev-parse", branch), n_files
    finally:
        git("worktree", "remove", "--force", wt, check=False)


def push(branch, remote, force, remote_branch="master", hint=None):
    """Publish `branch` to `remote`'s `remote_branch`, refusing to clobber.

    Two publish targets share this path, because both can receive edits made in
    the Overleaf editor and both must refuse to overwrite them:

      overleaf     Overleaf's own git remote; its only branch is master.
      thesis-repo  a GitHub repository whose root is the project, linked to
                   Overleaf through Menu -> GitHub. Overleaf's GitHub
                   integration pushes editor changes *back* into that
                   repository, so the guard matters more here, not less.
    """
    if subprocess.run(["git", "-C", ROOT, "remote", "get-url", remote],
                      capture_output=True).returncode:
        raise SystemExit(
            f"ERROR: no '{remote}' remote. See thesis/OVERLEAF_SYNC.md:\n"
            f"  {hint or f'git remote add {remote} https://git.overleaf.com/<project-id>'}")

    ref = f"{remote}/{remote_branch}"
    fetched = subprocess.run(["git", "-C", ROOT, "fetch", remote, remote_branch],
                             capture_output=True, text=True)
    if fetched.returncode:
        # An empty repository has no branch to fetch yet; that is the normal
        # first publish, not a failure worth blocking on.
        print(f"  note: could not fetch {ref} (new or empty target?), "
              f"pushing without the overwrite check")
    else:
        head = git("rev-parse", "FETCH_HEAD")
        ahead = git("rev-list", f"{branch}..{head}")
        if ahead and not force:
            n = len(ahead.split())
            log = git("log", "--oneline", f"{branch}..{head}")
            raise SystemExit(
                f"REFUSING TO PUSH: {ref} has {n} commit(s) this branch does "
                f"not have -- edits made in Overleaf:\n{log}\n\n"
                f"This sync is one-way: annotations are stripped on the way "
                f"out, so those edits cannot be replayed into thesis/ "
                f"automatically. Port them into thesis/ by hand, re-run this "
                f"script, then push. To discard them instead: --force.")

    print(f">> Pushing {branch} to {ref} ...")
    subprocess.run(["git", "-C", ROOT, "push", remote,
                    f"{branch}:{remote_branch}", *(["--force"] if force else [])],
                   check=True)


def push_origin(branch):
    """Mirror the generated branch to origin as well.

    Overleaf's remote is the publish target; origin is where the rest of the
    project lives, so keeping a copy there makes the published state visible
    (and recoverable) without Overleaf credentials. The branch is append-only,
    so this fast-forwards.
    """
    print(f">> Mirroring {branch} to origin ...")
    subprocess.run(["git", "-C", ROOT, "push", "origin", branch], check=True)


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--push", action="store_true", help="push the branch to Overleaf")
    ap.add_argument("--force", action="store_true",
                    help="push even if Overleaf has edits this branch lacks (discards them)")
    ap.add_argument("--branch", default=DEFAULT_BRANCH)
    ap.add_argument("--remote", default=DEFAULT_REMOTE)
    ap.add_argument("--mode", default="clean", choices=("clean", "annotated"),
                    help="clean (default) strips the \\REV fix records")
    ap.add_argument("--repo", action="store_true",
                    help=f"publish to the '{REPO_REMOTE}' remote's "
                         f"{REPO_BRANCH} branch -- a GitHub repository whose "
                         f"root is the project, for Overleaf's GitHub integration")
    ap.add_argument("--repo-remote", default=REPO_REMOTE)
    ap.add_argument("--repo-branch", default=REPO_BRANCH)
    ap.add_argument("--origin", action="store_true",
                    help="also mirror the branch to origin (visibility/backup copy)")
    ap.add_argument("--show", action="store_true",
                    help="list what the project resolves to and exit")
    a = ap.parse_args()

    if a.show:
        man = manifest()
        print(f"main.tex + {len(man['chapters'])} chapters + references.bib")
        for c in man["chapters"]:
            print(f"    chapters/{c}.tex")
        print(f"  {len(man['figures'])} figures, "
              f"styles: {', '.join(man['styles']) or 'none'}")
        return 0

    if ensure_branch(a.branch):
        print(f"  created branch {a.branch}")
    changed, sha, n_files = publish(a.branch, a.mode)
    print(f"  {a.branch} {'updated' if changed else 'already current'} "
          f"at {sha[:9]}: {n_files} files ({a.mode})")

    if a.origin:
        push_origin(a.branch)
    if a.repo:
        push(a.branch, a.repo_remote, a.force,
             remote_branch=a.repo_branch, hint=REPO_HINT)
    if a.push:
        push(a.branch, a.remote, a.force)
    elif not (a.origin or a.repo):
        print(f"  not pushed. To publish:  python3 scripts/overleaf_sync.py --push")
    return 0


if __name__ == "__main__":
    sys.exit(main())
